server:
  port: 8075
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-server-1.com
  client:
    serviceUrl:
      defaultZone: http://eureka-server-2.com:8076/eureka,http://eureka-server-3.com:8077/eureka
    register-with-eureka: false
