server:
  port: 8090
spring:
  application:
    name: client
  mvc:
    static-path-pattern: /**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1.com:8075/eureka,http://eureka-server-2.com:8076/eureka,http://eureka-server-3.com:8077/eureka
    register-with-eureka: true
    fetch-registry: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


